[build]
  command = "yarn build"
  publish = "out"
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[template]
  incoming-hooks = ["strapi-update"]

[template.environment]
NEXT_PUBLIC_STRAPI_API_URL="https://yourherokuappname.herokuapp.com"


